### ISSUE TITLE
devs.orbisgis.org certificate

### ISSUE THREAD

**Issue by Nitnelav** [orbisgis/orbisrcp#42]
The certificate for https://devs.orbisgis.org/eclipse-repo-snapshot/ is outdated it seems...
The https://devs.orbisgis.org/eclipse-repo/ returns 404

**Comment by ebocher** [comment]
In relation with the OVH crash
@SPalominos  what do you think?

**Comment by SPalominos** [comment]
I will renew the certificate today, it should fix the issue.

**Comment by ebocher** [comment]
@SPalominos is it fixed ?
