### ISSUE TITLE
Remove H2GIS snapshot workaround

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisrcp#72]
Currently, the workaround #71 is done to be able to load H2GIS snapshot. 
As the H2GIS modules version are defined using pom properties, they can't be resolved with maven because DBeaver can't parse those properties : dbeaver/dbeaver#15556.
We also have to find if and how DBeaver can resolve OSSRH snapshot repository artifacts to avoid hard writing of jar to load.

**Comment by ebocher** [comment]
It seems fixed now on dbeaver side
